### ISSUE TITLE
Make the API flexible to conform both with Accept interface (like net.connect pattern) and HandlerFunc (like http pattern)

### ISSUE THREAD

**Issue by diasdavid** [diasdavid/abstract-stream-muxer#1]
//cc @mafintosh

- Have dialStream always return the stream obj and buffer the writes until it is ready.
- Call the callback with (err, stream) when the stream is ready.

Thanks for bringing this up :)

**Comment by diasdavid** [comment]
@mafintosh updated the spec, tests and spdy-stream-muxer and multiplex-stream-muxer, let me know if I managed to get what you were looking for, right :)

**Comment by mafintosh** [comment]
@diasdavid this is perfect! thanks
